# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Headless Rodeo 
email: headlessmanhorse@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  "HQ of Headless Rodeo & Ooze's blog (that's me) & any other random stuff"
twitter_username: username
github_username: bigooze
minimal_mistakes_skin: "contrast"
masthead_title: ""
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 8 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-include-cache

author:
  name   : "ooze"
  avatar : "/assets/images/slimer.png"
  bio    : "started from the sewer now i'm here."
  location: "Under a rock in Phoenix"
  links:

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    
    - label: "Red Sands Meetup"
      icon: "fab fa-fw fa-meetup"
      url: "https://www.meetup.com/redsands/"
    - label: "Etsy Store> Headless Man-Horse"
      icon: "fa fa-heart"
      url: "https://www.etsy.com/shop/headlessmanhorse"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Etsy Store"
      icon: "fa fa-heart"
      url: "https://www.etsy.com/shop/headlessmanhorse"




collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  art:
    output: true
  journal:
    output: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      date_format: "%Y-%m-%d"
      read_time: false
      comments: false
      share: false
      related: true
      header:
        teaser: /assets/images/cog_big.jpg
        
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true


search: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

year_archive:
  type: liquid
  path: /year/